#!/usr/bin/env python3
"""
Canada WNT — scouting report.
All text analysis generated by Claude AI (claude-opus-4-8).
Shot charts use exact SSA polygon shapes + real SSA court background image.
"""
import sqlite3, os, sys, json, urllib.request, base64
from html import escape

# Load .env manually — no dotenv dependency required
_env = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
if os.path.exists(_env):
    for line in open(_env):
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH  = os.path.join(BASE_DIR, "data", "db", "ssa.db")

# ── Court PNG — keep as local file next to the HTML output ────────────────────
COURT_PNG_URL  = "https://www.strongsideanalytics.com/assets/images/shooting-map-sm.png"
COURT_PNG_LOCAL = os.path.join(BASE_DIR, "shooting-map-sm.png")  # sits beside the HTML

def ensure_court_png():
    if not os.path.exists(COURT_PNG_LOCAL):
        print("Downloading court background image from SSA...", flush=True)
        urllib.request.urlretrieve(COURT_PNG_URL, COURT_PNG_LOCAL)
    print(f"Court image ready: {COURT_PNG_LOCAL}", flush=True)

# ── Exact SSA zone polygon coordinates (viewBox 0 0 1905 1787) ───────────────
# Extracted directly from the SSA Angular SVG in DevTools
SSA_ZONE_POLYGONS = {
    "TWO_POINTS_LAYUP_LEFT":
        "955,545 955,58 708,58 686,90 669,119 659,146 648,179 643,217 642,247 "
        "643,279 651,307 661,342 673,373 692,400 709,424 731,454 755,473 787,495 "
        "817,513 852,526 899,540",
    "TWO_POINTS_LAYUP_RIGHT":
        "955,547 955,56 1195,57 1228,104 1248,147 1258,199 1261,247 1258,290 "
        "1244,333 1230,370 1211,404 1184,440 1150,474 1111,498 1072,521 1029,534 989,543",
    "TWO_POINTS_MID_LEFT_WING":
        "405,57 692,54 671,86 654,121 642,150 634,181 632,198 627,222 627,248 "
        "628,273 632,306 636,327 647,353 655,376 666,396 678,416 692,434 706,452 "
        "720,470 737,485 755,494 677,748 623,715 577,677 538,639 507,603 484,573 "
        "461,540 437,504 422,467 409,428 396,393 385,346 378,312 377,273 374,226 "
        "379,186 385,134 391,93",
    "TWO_POINTS_MID_TOP":
        "768,504 687,755 732,777 768,789 795,798 821,806 844,812 870,816 899,820 "
        "928,821 961,821 994,820 1025,816 1059,810 1090,804 1125,793 1154,782 "
        "1179,773 1215,756 1138,502 1119,516 1102,526 1076,537 1049,545 1021,553 "
        "993,559 962,561 928,560 901,560 881,555 858,547 829,534 805,525",
    "TWO_POINTS_MID_RIGHT_WING":
        "1216,57 1507,58 1518,86 1526,124 1531,154 1535,181 1536,213 1535,248 "
        "1535,277 1532,306 1530,334 1526,357 1520,380 1509,413 1497,448 1483,486 "
        "1466,510 1450,540 1431,568 1409,600 1386,625 1361,651 1337,673 1309,695 "
        "1281,716 1232,750 1152,497 1179,470 1209,434 1228,407 1247,377 1257,347 "
        "1270,304 1275,252 1274,213 1270,174 1261,142 1247,108 1234,78",
    "TWO_POINTS_LONG_LEFT_CORNER":
        "183,57 391,56 369,121 357,181 354,232 354,272 355,306 359,337 366,369 "
        "373,401 382,432 391,459 404,486 414,508 428,533 444,557 456,576 227,764 190,712",
    "TWO_POINTS_LONG_LEFT_WING":
        "238,782 474,594 513,639 542,672 570,697 600,719 631,740 657,755 681,770 "
        "712,785 735,789 652,1062 589,1039 535,1013 490,988 448,962 408,937 374,910 "
        "342,883 313,856 287,832 260,804",
    "TWO_POINTS_LONG_TOP":
        "665,1065 748,799 803,818 842,828 872,830 899,833 930,836 955,837 987,834 "
        "1026,830 1056,826 1083,821 1119,812 1160,799 1248,1066 1250,1070 1212,1081 "
        "1168,1091 1123,1101 1083,1108 1040,1113 1001,1117 965,1120 931,1120 889,1117 "
        "852,1114 811,1108 768,1098 718,1085",
    "TWO_POINTS_LONG_RIGHT_WING":
        "1179,791 1262,1062 1300,1051 1339,1034 1374,1017 1410,995 1435,981 1469,958 "
        "1504,934 1536,910 1573,884 1604,849 1627,825 1672,781 1435,588 1418,618 "
        "1388,649 1360,678 1325,707 1292,732 1258,754 1228,769 1205,779",
    "TWO_POINTS_LONG_RIGHT_CORNER":
        "1524,58 1723,57 1726,711 1683,763 1448,577 1484,518 1504,478 1516,443 "
        "1528,405 1540,361 1547,321 1551,280 1551,240 1551,213 1550,179 1544,146 1536,103",
    "THREE_POINTS_LEFT_CORNER":  "52,57 160,56 159,713 54,715",
    "THREE_POINTS_LEFT_WING":
        "55,731 160,731 191,771 215,798 239,824 264,851 295,879 322,907 351,929 "
        "383,953 410,973 443,995 474,1013 510,1032 548,1054 588,1071 627,1086 "
        "679,1104 542,1733 55,1733",
    "THREE_POINTS_TOP":
        "1224,1105 1359,1733 560,1734 692,1108 736,1120 786,1129 838,1137 884,1141 "
        "934,1145 979,1147 1021,1145 1066,1140 1100,1134 1137,1128 1181,1118",
    "THREE_POINTS_RIGHT_WING":
        "1857,727 1855,1732 1375,1732 1239,1104 1305,1078 1359,1055 1418,1021 "
        "1464,996 1501,970 1544,938 1578,917 1609,886 1640,855 1674,820 1698,793 "
        "1725,759 1752,725",
    "THREE_POINTS_RIGHT_CORNER": "1752,58 1858,58 1858,709 1752,709",
}

# Label centres lifted directly from SSA SVG <text> elements
SSA_TEXT_POS = {
    "TWO_POINTS_LAYUP_LEFT":         (810,  310, 370),
    "TWO_POINTS_LAYUP_RIGHT":        (1080, 310, 370),
    "TWO_POINTS_MID_LEFT_WING":      (518,  344, 404),
    "TWO_POINTS_MID_TOP":            (944,  699, 759),
    "TWO_POINTS_MID_RIGHT_WING":     (1374, 399, 459),
    "TWO_POINTS_LONG_LEFT_CORNER":   (263,  499, 559),
    "TWO_POINTS_LONG_LEFT_WING":     (489,  825, 885),
    "TWO_POINTS_LONG_TOP":           (957,  1000, 1060),
    "TWO_POINTS_LONG_RIGHT_WING":    (1404, 850, 910),
    "TWO_POINTS_LONG_RIGHT_CORNER":  (1600, 557, 617),
    "THREE_POINTS_LEFT_CORNER":      (100,  310, 370),
    "THREE_POINTS_LEFT_WING":        (301,  1096, 1156),
    "THREE_POINTS_TOP":              (957,  1280, 1340),
    "THREE_POINTS_RIGHT_WING":       (1600, 1071, 1131),
    "THREE_POINTS_RIGHT_CORNER":     (1804, 310, 370),
}

def zone_fill(pct, total):
    """Return (fill_color, opacity) matching SSA's percentage-based coloring."""
    if total == 0:  return "transparent", 0
    if pct >= 55:   return "#4CAF50", 0.75   # green  — hot
    if pct >= 40:   return "#FFC107", 0.75   # amber  — warm
    if pct >= 25:   return "#FF7043", 0.75   # orange — below avg
    return "#EF5350", 0.75                   # red    — cold

def make_court_svg(zone_data: dict, title: str) -> str:
    """Build SVG using exact SSA polygon shapes + real court background (local file)."""
    lines = [
        f'<div style="text-align:center">',
        f'<div style="font-size:9px;font-weight:bold;color:#555;margin-bottom:2px;text-transform:uppercase">{title}</div>',
        f'<svg viewBox="0 0 1905 1787" preserveAspectRatio="xMidYMid meet" '
        f'xmlns="http://www.w3.org/2000/svg" '
        f'style="width:100%;max-width:280px;display:block;margin:auto;border-radius:4px;border:1px solid #ccc">',
        # Court background — local file, no base64 bloat
        f'<image href="shooting-map-sm.png" width="100%" height="100%"/>',
    ]

    # Draw each zone polygon, coloured by efficiency
    for zone, pts in SSA_ZONE_POLYGONS.items():
        d      = zone_data.get(zone, {})
        total  = d.get("total", 0)
        pct    = d.get("pct",   0.0)
        fill, opacity = zone_fill(pct, total)
        lines.append(
            f'<polygon points="{pts}" fill="{fill}" fill-opacity="{opacity}" '
            f'stroke="rgba(255,255,255,0.25)" stroke-width="2" data-zone="{zone}"/>'
        )

    # Text labels (pct + made/total)
    for zone, (tx, ty_pct, ty_mt) in SSA_TEXT_POS.items():
        d     = zone_data.get(zone, {})
        total = d.get("total", 0)
        made  = d.get("made",  0)
        pct   = d.get("pct",   0.0)
        if total > 0:
            lines.append(
                f'<text text-anchor="middle" font-size="72" font-weight="700" '
                f'fill="white" stroke="rgba(0,0,0,0.5)" stroke-width="8" paint-order="stroke" '
                f'x="{tx}" y="{ty_pct}">{pct:.0f}%</text>'
            )
            lines.append(
                f'<text text-anchor="middle" font-size="58" '
                f'fill="white" stroke="rgba(0,0,0,0.5)" stroke-width="6" paint-order="stroke" '
                f'x="{tx}" y="{ty_mt}">{made}/{total}</text>'
            )

    # Legend — bottom-right corner of the SVG
    leg = [("#4CAF50","≥55%"),("#FFC107","40–55%"),("#FF7043","25–40%"),("#EF5350","<25%")]
    for i, (clr, lbl) in enumerate(leg):
        lx = 1350 + i * 130
        lines.append(f'<rect x="{lx}" y="1740" width="28" height="28" fill="{clr}" rx="4"/>')
        lines.append(f'<text x="{lx+36}" y="1762" font-size="36" fill="white" '
                     f'stroke="rgba(0,0,0,0.5)" stroke-width="4" paint-order="stroke">{lbl}</text>')

    lines += ['</svg>', '</div>']
    return "\n".join(lines)

# ── DB helpers ────────────────────────────────────────────────────────────────

def q(conn, sql, *args):
    return conn.execute(sql, args).fetchall()

CT = "NATIONAL_TEAMS"

def fetch_zone_data(conn, pid, period, is_dribble):
    rows = q(conn, "SELECT zone,made,missed,total,pct FROM player_shot_zones WHERE player_id=? AND period=? AND is_dribble=? AND competition_type=?", pid, period, is_dribble, CT)
    return {r["zone"]: dict(r) for r in rows}

def fetch_stats(conn, pid, period):
    rows = q(conn, "SELECT stat_label,total,per_game FROM player_stats WHERE player_id=? AND period=? AND competition_type=?", pid, period, CT)
    return {r["stat_label"]: dict(r) for r in rows}

def fetch_play_types(conn, pid, period):
    rows = q(conn, "SELECT play_type,poss,ppp,usage,two_pt_m,two_pt_a,two_pt_pct,three_pt_m,three_pt_a,three_pt_pct,turnovers FROM player_play_types_detail WHERE player_id=? AND period=? AND competition_type=? ORDER BY usage DESC", pid, period, CT)
    return [dict(r) for r in rows if r["usage"] > 0]

def fetch_finishing(conn, pid, period):
    rows = q(conn, "SELECT shot_type,hand,made,attempted,pct FROM player_tendency_finishing WHERE player_id=? AND period=? AND competition_type=? AND attempted>0", pid, period, CT)
    return {(r["shot_type"], r["hand"]): dict(r) for r in rows}

def fetch_turnovers(conn, pid, period):
    rows = q(conn, "SELECT play_type,bad_pass,traveling,total FROM player_turnovers WHERE player_id=? AND period=? AND competition_type=? AND total>0 ORDER BY total DESC", pid, period, CT)
    return [dict(r) for r in rows]

def fetch_shooting_tendency(conn, pid, period):
    rows = q(conn, "SELECT category,hand,two_pt_m,two_pt_a,two_pt_pct FROM player_tendency_shooting WHERE player_id=? AND period=? AND competition_type=?", pid, period, CT)
    return {(r["category"], r["hand"]): dict(r) for r in rows}

# ── Helpers ───────────────────────────────────────────────────────────────────

PT_LABELS = {
    "PICK_AND_ROLL": "Pick & Roll", "HANDOFF": "Handoff", "OFFSCREEN": "Off Screen",
    "TRANSITION": "Transition", "CUT": "Cut", "POST_UP": "Post Up",
    "SPOT_UP": "Spot Up", "OFFENSIVE_REBOUND": "Off. Rebound",
    "ISOLATION": "Isolation", "NO_PLAY_TYPES": "Unclassified",
}
def ppt(s): return PT_LABELS.get(s, s)
def sv(d, key, field="per_game"): return d.get(key, {}).get(field, 0.0) or 0.0
def pct_cls(v):
    if v >= 55: return "hot"
    if v >= 40: return "warm"
    if v <  25: return "cold"
    return ""
def ppp_cls(v):
    if v >= 0.60: return "hot"
    if v <  0.35: return "cold"
    return ""
def cm_to_ft(cm):
    if not cm: return "?"
    t = cm / 2.54
    return f"{int(t//12)}'{int(round(t%12))}\""

# ── Claude API — direct HTTP, no SDK dependency ───────────────────────────────

import urllib.request as _urlreq

def claude(prompt: str, max_tokens: int = 600) -> str:
    """Call Claude claude-opus-4-8 via raw HTTP. Returns response text."""
    key = os.getenv("ANTHROPIC_API_KEY", "")
    if not key:
        raise RuntimeError("ANTHROPIC_API_KEY not set")
    body = json.dumps({
        "model": "claude-opus-4-8",
        "max_tokens": max_tokens,
        "messages": [{"role": "user", "content": prompt}],
    }).encode()
    req = _urlreq.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "x-api-key": key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        method="POST",
    )
    with _urlreq.urlopen(req, timeout=120) as resp:
        return json.loads(resp.read())["content"][0]["text"]

SCORING_CTX = (
    "3x3 SCORING: inside arc = 1pt (DB stat: 2PT%/2PTM/2PTA → write '1PT'); "
    "outside arc = 2pt (DB stat: 3PT%/3PTM/3PTA → write '2PT'); FT = 1pt (DB: 1PT%)."
)

def build_player_summary(name, stats, pts, fin, tvs, tend, z0, z1):
    def gs(l): return stats.get(l, {}).get("per_game", 0) or 0
    lines = [
        f"PLAYER: {name}",
        f"GP={gs('GAMES_PLAYED'):.0f}  PPG={gs('POINTS'):.1f}  PPP={gs('POINTS_PER_POSSESSIONS'):.2f}",
        f"Inside (1PT): {gs('2PTM'):.1f}/{gs('2PTA'):.1f} ({gs('2PT%'):.0f}%)",
        f"Outside (2PT): {gs('3PTM'):.1f}/{gs('3PTA'):.1f} ({gs('3PT%'):.0f}%)",
        f"FT: {gs('1PTM'):.1f}/{gs('1PTA'):.1f} ({gs('1PT%'):.0f}%)",
        f"ORB={gs('OFFENSIVE_REBOUNDS'):.1f}  DRB={gs('DEFENSIVE_REBOUNDS'):.1f}  "
        f"TO={gs('TURNOVERS'):.1f}  FD={gs('FOULS_AGAINST'):.1f}  FC={gs('FOULS'):.1f}  STL={gs('STEALS'):.1f}",
        "\nPlay Types (usage%, PPP, 1PT m/a%, 2PT m/a%, TOs):",
    ]
    for r in pts[:7]:
        lines.append(
            f"  {ppt(r['play_type'])}: {r['usage']:.0f}% usage  {r['ppp']:.2f} PPP  "
            f"1PT {r['two_pt_m']}/{r['two_pt_a']} ({r['two_pt_pct']:.0f}%)  "
            f"2PT {r['three_pt_m']}/{r['three_pt_a']} ({r['three_pt_pct']:.0f}%)  TO={r['turnovers']}"
        )
    lines.append("\nRim Finishing (shot/hand: made/att pct%):")
    for (st, hand), d in fin.items():
        lines.append(f"  {st}/{hand}: {d['made']}/{d['attempted']} ({d['pct']:.0f}%)")
    lines.append("\nShooting Tendency (cat/hand: m/a pct%):")
    for (cat, hand), d in tend.items():
        lines.append(f"  {cat}/{hand}: {d['two_pt_m']}/{d['two_pt_a']} ({d['two_pt_pct']:.0f}%)")
    if tvs:
        lines.append("\nTurnovers by play type:")
        for r in tvs:
            lines.append(f"  {ppt(r['play_type'])}: {r['total']} (bad_pass={r['bad_pass']} travel={r['traveling']})")
    lines.append("\nZones — No Dribble:")
    for zone, d in z0.items():
        if d.get("total", 0) > 0:
            lines.append(f"  {zone}: {d['made']}/{d['total']} ({d['pct']:.0f}%)")
    lines.append("\nZones — Off Dribble:")
    for zone, d in z1.items():
        if d.get("total", 0) > 0:
            lines.append(f"  {zone}: {d['made']}/{d['total']} ({d['pct']:.0f}%)")
    return "\n".join(lines)


def claude_player_insights(name, stats, pts, fin, tvs, tend, z0, z1):
    """AI-generated exploitation bullets. Returns list of (text, css_class)."""
    data = build_player_summary(name, stats, pts, fin, tvs, tend, z0, z1)
    prompt = f"""{SCORING_CTX}

You are a 3x3 basketball analyst writing a scouting report for an opposing coaching staff.
Below is all season data for {name}. Only use numbers from this data — zero hallucination.

{data}

Generate exactly 5 bullet points on HOW TO EXPLOIT {name} — specific attack plan backed by exact numbers.
Tag each bullet at the start:
  [ATTACK] = weakness / how to attack them
  [AVOID]  = their strength / what NOT to give them

Rules: cover scoring weakness, weak finishing hand, leaky play type, zone to target, turnover trigger.
Keep each bullet under 28 words. Output: one bullet per line, tag first — no other formatting."""

    raw = claude(prompt, max_tokens=500).strip()
    bullets = []
    for line in raw.splitlines():
        line = line.strip().lstrip("•·-–*").strip()
        if not line: continue
        if line.startswith("[AVOID]"):
            bullets.append((line[7:].strip(), "note-caution"))
        elif line.startswith("[ATTACK]"):
            bullets.append((line[8:].strip(), "note-exploit"))
        else:
            lower = line.lower()
            cls = "note-caution" if any(w in lower for w in ["do not","avoid","danger","strong","elite","threat"]) else "note-exploit"
            bullets.append((line, cls))
    print(f"    {name}: {len(bullets)} insight bullets")
    return bullets[:6]


def build_team_summary(conn, team_players, all_ids, period):
    lines = [f"TEAM: Canada WNT | {SCORING_CTX}",
             "\nROSTER (PPG, PPP, 1PT%, 2PT%, FT%, ORB, DRB, STL, TO, FD, FC):"]
    for p in team_players:
        s = fetch_stats(conn, p["id"], period)
        def gs(l): return s.get(l, {}).get("per_game", 0) or 0
        lines.append(
            f"  #{p['jersey_number']} {p['full_name']}: GP={gs('GAMES_PLAYED'):.0f} "
            f"PPG={gs('POINTS'):.1f} PPP={gs('POINTS_PER_POSSESSIONS'):.2f} "
            f"1PT%={gs('2PT%'):.0f} 2PT%={gs('3PT%'):.0f} FT%={gs('1PT%'):.0f} "
            f"ORB={gs('OFFENSIVE_REBOUNDS'):.1f} DRB={gs('DEFENSIVE_REBOUNDS'):.1f} "
            f"STL={gs('STEALS'):.1f} TO={gs('TURNOVERS'):.1f} "
            f"FD={gs('FOULS_AGAINST'):.1f} FC={gs('FOULS'):.1f}"
        )
    team_pts = conn.execute(
        f"SELECT play_type, SUM(poss) tot, SUM(poss*ppp)/NULLIF(SUM(poss),0) wppp "
        f"FROM player_play_types_detail WHERE player_id IN ({all_ids}) AND period='{period}' AND competition_type='{CT}' AND poss>0 "
        f"GROUP BY play_type ORDER BY tot DESC"
    ).fetchall()
    grand = sum(r["tot"] for r in team_pts if r["tot"]) or 1
    lines.append("\nTEAM OFFENSIVE PLAY TYPES (poss%, weighted PPP):")
    for r in team_pts:
        if (r["tot"] or 0) >= 3:
            lines.append(f"  {ppt(r['play_type'])}: {100*r['tot']/grand:.1f}% poss  {(r['wppp'] or 0):.2f} PPP")
    lines.append("\nDEFENSIVE PLAY TYPES (PPP allowed, top actions per player):")
    for p in team_players:
        defense = conn.execute(
            "SELECT label,ppp,possession FROM player_play_types WHERE player_id=? AND period=? AND competition_type=? AND side='defense' ORDER BY possession DESC",
            (p["id"], period, CT)
        ).fetchall()
        if defense:
            ds = "  ".join(f"{ppt(d['label'])}:{d['ppp']:.2f}({d['possession']}poss)" for d in defense[:4])
            lines.append(f"  {p['full_name']}: {ds}")
    lines.append("\nTURNOVERS per player (top actions):")
    for p in team_players:
        tvs = conn.execute(
            "SELECT play_type,bad_pass,traveling,total FROM player_turnovers WHERE player_id=? AND period=? AND competition_type=? AND total>0 ORDER BY total DESC LIMIT 3",
            (p["id"], period, CT)
        ).fetchall()
        if tvs:
            ts = "  ".join(f"{ppt(t['play_type'])}:{t['total']}(bp={t['bad_pass']},trv={t['traveling']})" for t in tvs)
            lines.append(f"  {p['full_name']}: {ts}")
    return "\n".join(lines)


def claude_team_sections(conn, team_players, all_ids, period):
    data = build_team_summary(conn, team_players, all_ids, period)
    prompt = f"""You are an elite 3x3 basketball analyst.
{SCORING_CTX}

Below is all season data for Canada WNT. Only use numbers from this data — zero hallucination.

{data}

Return VALID JSON only (no markdown, no fences) with exactly these 5 keys, each = array of 4–6 strings:
{{
  "offensive_profile": [...],
  "transition_foul": [...],
  "defence_overview": [...],
  "opponent_targets": [...],
  "turnovers": [...]
}}
Each string = one concise bullet (≤30 words) backed by exact numbers. No headers, no numbering."""

    raw = claude(prompt, max_tokens=2000).strip()
    if raw.startswith("```"): raw = "\n".join(raw.splitlines()[1:])
    if raw.endswith("```"):   raw = "\n".join(raw.splitlines()[:-1])
    # Extract JSON object robustly
    start = raw.find("{")
    end   = raw.rfind("}") + 1
    if start != -1 and end > start:
        raw = raw[start:end]
    try:
        return json.loads(raw)
    except Exception as e:
        print(f"  Team JSON parse error: {e}")
        return {"offensive_profile":["[Parse error]"],"transition_foul":[],"defence_overview":[],"opponent_targets":[],"turnovers":[]}


def bullets_html(items):
    html = ""
    for item in items:
        lower = item.lower()
        if any(w in lower for w in ["do not","avoid","danger","careful","threat","strong","elite","beware"]):
            cls = ' class="r"'
        elif any(w in lower for w in ["exploit","target","force","attack","pressure","push"]):
            cls = ' class="g"'
        else:
            cls = ""
        html += f"<li{cls}>{escape(item)}</li>\n"
    return html

# ── Player card ───────────────────────────────────────────────────────────────

def player_card(conn, p, period):
    pid  = p["id"]
    name = p["full_name"]
    pos  = (p["position"] or "").replace("CENTER","C").replace("FORWARD","F").replace("GUARD","G")
    ht   = cm_to_ft(p["height"])
    jnum = p["jersey_number"] or "?"

    stats = fetch_stats(conn, pid, period)
    pts   = fetch_play_types(conn, pid, period)
    fin   = fetch_finishing(conn, pid, period)
    tvs   = fetch_turnovers(conn, pid, period)
    tend  = fetch_shooting_tendency(conn, pid, period)
    z0    = fetch_zone_data(conn, pid, period, 0)
    z1    = fetch_zone_data(conn, pid, period, 1)

    gp     = int(sv(stats,"GAMES_PLAYED") or 0)
    ppg    = sv(stats,"POINTS"); ppp = sv(stats,"POINTS_PER_POSSESSIONS")
    one_m  = sv(stats,"2PTM"); one_a = sv(stats,"2PTA"); one_pct = sv(stats,"2PT%")
    two_m  = sv(stats,"3PTM"); two_a = sv(stats,"3PTA"); two_pct = sv(stats,"3PT%")
    ft_m   = sv(stats,"1PTM"); ft_a  = sv(stats,"1PTA"); ft_pct  = sv(stats,"1PT%")
    reb    = round(sv(stats,"DEFENSIVE_REBOUNDS") + sv(stats,"OFFENSIVE_REBOUNDS"), 1)
    fd     = sv(stats,"FOULS_AGAINST"); fc = sv(stats,"FOULS")

    pt_rows = ""
    for r in pts[:5]:
        ppp_v = r["ppp"] or 0
        o1p   = f'{r["two_pt_pct"]:.0f}%'  if r["two_pt_a"]   > 0 else "—"
        o2p   = f'{r["three_pt_pct"]:.0f}%' if r["three_pt_a"] > 0 else "—"
        to    = r["turnovers"]
        pt_rows += (
            f'<tr><td>{ppt(r["play_type"])}</td><td>{r["usage"]:.0f}%</td>'
            f'<td class="{ppp_cls(ppp_v)}">{ppp_v:.2f}</td>'
            f'<td class="{pct_cls(r["two_pt_pct"] if r["two_pt_a"]>0 else 30)}">{o1p}</td>'
            f'<td class="{pct_cls(r["three_pt_pct"] if r["three_pt_a"]>0 else 30)}">{o2p}</td>'
            f'<td{"  class=\"warn-to\"" if to>=2 else ""}>{to}</td></tr>\n'
        )

    f_rh = fin.get(("LAYUP","RIGHT"), {}); f_lh = fin.get(("LAYUP","LEFT"), {})
    rim  = fin.get(("ALL","ALL"), {})
    rt   = rim.get("attempted", 0)
    fin_line = (
        f'<b>{rim.get("made",0)}/{rt} ({rim.get("pct",0):.0f}%)</b> &nbsp;·&nbsp; '
        f'RH {f_rh.get("made",0)}/{f_rh.get("attempted",0)} ({f_rh.get("pct",0):.0f}%) '
        f'&nbsp;·&nbsp; LH {f_lh.get("made",0)}/{f_lh.get("attempted",0)} ({f_lh.get("pct",0):.0f}%)'
    ) if rt > 0 else "No rim attempts"

    dj  = tend.get(("DRIBBLE_JUMPER","ALL"),{})
    djr = tend.get(("DRIBBLE_JUMPER","RIGHT"),{})
    djl = tend.get(("DRIBBLE_JUMPER","LEFT"),{})
    ndj = tend.get(("NO_DRIBBLE_JUMPER","ALL"),{})
    dj_line = (
        f'Pull-up: <b>{dj.get("two_pt_m",0)}/{dj.get("two_pt_a",0)} ({dj.get("two_pt_pct",0):.0f}%)</b> '
        f'[RH {djr.get("two_pt_m",0)}/{djr.get("two_pt_a",0)} · LH {djl.get("two_pt_m",0)}/{djl.get("two_pt_a",0)}] '
        f'&nbsp;·&nbsp; C&amp;S: <b>{ndj.get("two_pt_m",0)}/{ndj.get("two_pt_a",0)} ({ndj.get("two_pt_pct",0):.0f}%)</b>'
    )

    to_pg  = sv(stats,"TURNOVERS")
    to_tags = " ".join(f'<span class="to-tag">{ppt(r["play_type"])} ×{r["total"]}</span>' for r in tvs[:3]) or "—"

    print(f"  Generating Claude insights for {name}...", flush=True)
    bullets = claude_player_insights(name, stats, pts, fin, tvs, tend, z0, z1)
    note_html = "\n".join(f'<li class="{cls}">{escape(text)}</li>' for text, cls in bullets)

    svg0 = make_court_svg(z0, "No Dribble (Catch &amp; Shoot)")
    svg1 = make_court_svg(z1, "Off Dribble")

    return f"""
<div class="pcard">
  <div class="pheader">
    <span class="pnum">#{jnum}</span>
    <span class="pname">{escape(name)}</span>
    <span class="pmeta">{pos} &nbsp;·&nbsp; {ht} &nbsp;·&nbsp; {gp} GP</span>
  </div>
  <div class="statbar">
    <div class="sc"><div class="sh">1PT (inside)</div><div class="sv">{one_m:.1f}/{one_a:.1f}</div><div class="sp {pct_cls(one_pct)}">{one_pct:.0f}%</div></div>
    <div class="sc"><div class="sh">2PT (arc)</div><div class="sv">{two_m:.1f}/{two_a:.1f}</div><div class="sp {pct_cls(two_pct)}">{two_pct:.0f}%</div></div>
    <div class="sc"><div class="sh">FT</div><div class="sv">{ft_m:.1f}/{ft_a:.1f}</div><div class="sp">{ft_pct:.0f}%</div></div>
    <div class="sc"><div class="sh">PPG</div><div class="sv">{ppg:.1f}</div></div>
    <div class="sc"><div class="sh">PPP</div><div class="sv {ppp_cls(ppp)}">{ppp:.2f}</div></div>
    <div class="sc"><div class="sh">REB</div><div class="sv">{reb}</div></div>
    <div class="sc"><div class="sh">FD</div><div class="sv">{fd:.1f}</div></div>
    <div class="sc"><div class="sh">FC</div><div class="sv">{fc:.1f}</div></div>
  </div>
  <div class="pbody">
    <div class="pleft">
      <div class="stitle">Play Types (Offense)</div>
      <table class="ptt">
        <thead><tr><th>Action</th><th>Usage</th><th>PPP</th><th>1PT%</th><th>2PT%</th><th>TO</th></tr></thead>
        <tbody>{pt_rows}</tbody>
      </table>
      <div class="stitle" style="margin-top:8px">Finishing &amp; Shooting</div>
      <div class="infoline">&#11044; Rim: {fin_line}</div>
      <div class="infoline">&#11044; Arc: {dj_line}</div>
      <div class="infoline">&#11044; TO {to_pg:.1f}/game: {to_tags}</div>
      <div class="stitle ai-title" style="margin-top:8px">&#129302; How to Exploit — Claude AI</div>
      <ul class="notes">{note_html}</ul>
    </div>
    <div class="pright">
      <div class="stitle">Shot Charts — Season (SSA zones)</div>
      <div class="chartrow">{svg0}{svg1}</div>
    </div>
  </div>
</div>"""

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if not os.getenv("ANTHROPIC_API_KEY"):
        print("Missing ANTHROPIC_API_KEY in .env")
        sys.exit(1)

    ensure_court_png()

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    players = conn.execute(
        "SELECT p.id, p.full_name, p.position, p.height, p.jersey_number "
        "FROM players p JOIN teams t ON p.team_id=t.id "
        "WHERE t.name='Canada WNT' ORDER BY CAST(p.jersey_number AS INTEGER), p.full_name"
    ).fetchall()
    team_players = [dict(p) for p in players]
    period  = "SEASON"
    all_ids = ",".join(f"'{p['id']}'" for p in team_players)

    team_pts = conn.execute(
        f"SELECT play_type, SUM(poss) tot, SUM(poss*ppp)/NULLIF(SUM(poss),0) wppp "
        f"FROM player_play_types_detail WHERE player_id IN ({all_ids}) AND period='{period}' AND competition_type='{CT}' AND poss>0 "
        f"GROUP BY play_type ORDER BY tot DESC"
    ).fetchall()
    grand = sum(r["tot"] for r in team_pts if r["tot"]) or 1
    tpt_rows = "".join(
        f'<tr><td>{ppt(r["play_type"])}</td><td>{100*r["tot"]/grand:.1f}%</td>'
        f'<td class="{ppp_cls(r["wppp"] or 0)}">{(r["wppp"] or 0):.2f}</td></tr>'
        for r in team_pts if (r["tot"] or 0) >= 3
    )

    print("Generating team-level AI analysis...", flush=True)
    team = claude_team_sections(conn, team_players, all_ids, period)
    off_html = bullets_html(team.get("offensive_profile", []))
    tr_html  = bullets_html(team.get("transition_foul",   []))
    def_html = bullets_html(team.get("defence_overview",  []))
    opp_html = bullets_html(team.get("opponent_targets",  []))
    to_html  = bullets_html(team.get("turnovers",         []))

    print("Generating player cards...", flush=True)
    card_list = [player_card(conn, p, period) for p in team_players]
    # Card 0 goes on the team overview page; cards 1-4 pair up (2+3, 4+5)
    first_card_html = card_list[0]
    paired = []
    for i in range(1, len(card_list), 2):
        pair = "\n".join(card_list[i:i+2])
        paired.append(f'<div class="page-pair">\n{pair}\n</div>')
    cards_html = "\n\n".join(paired)

    css = """
* { box-sizing:border-box; margin:0; padding:0; }
body { font-family: Arial, Helvetica, sans-serif; font-size:11px; color:#111;
       background:#fff; padding:16px; max-width:1340px; margin:auto; }
.hdr { text-align:center; border-bottom:3px solid #C8102E; padding-bottom:10px; margin-bottom:12px; }
.hdr h1 { font-size:24px; font-weight:900; color:#C8102E; letter-spacing:1px; }
.hdr .sub { font-size:11px; color:#666; margin-top:3px; }
.snote { background:#fff8e1; border:1px solid #ffe082; border-radius:3px;
         padding:5px 10px; font-size:10px; margin-bottom:12px; }
.snote b { color:#C8102E; }
.team-grid { display:grid; grid-template-columns:1fr 1fr 1fr; gap:10px; margin-bottom:12px; }
.def-grid  { display:grid; grid-template-columns:1fr 1fr 1fr; gap:10px; margin-bottom:14px; }
.box { border:1px solid #ddd; border-radius:4px; }
.boxtitle { background:#C8102E; color:white; font-weight:bold; font-size:10px;
            padding:4px 8px; border-radius:3px 3px 0 0; }
.defbox { border:1px solid #ddd; border-radius:4px; }
.deftitle { background:#1a1a2e; color:white; font-weight:bold; font-size:10px;
            padding:4px 8px; border-radius:3px 3px 0 0; }
.boxbody { padding:8px; }
.boxbody ul { padding-left:13px; }
.boxbody li { margin-bottom:3px; line-height:1.45; font-size:10.5px; }
.boxbody li.r { color:#C8102E; font-weight:600; }
.boxbody li.g { color:#2e7d32; font-weight:600; }
table.tpt { width:100%; border-collapse:collapse; }
table.tpt th { background:#555; color:white; padding:3px 5px; font-size:9.5px; text-align:left; }
table.tpt td { padding:2px 5px; border-bottom:1px solid #f0f0f0; font-size:10.5px; }
table.tpt tr:nth-child(even) td { background:#fafafa; }
.pcard { border:2px solid #1a1a2e; border-radius:5px; margin-bottom:16px; overflow:hidden; }
.pheader { background:#1a1a2e; color:white; padding:8px 12px; display:flex; align-items:center; gap:12px; }
.pnum { background:#C8102E; font-size:18px; font-weight:900; padding:3px 9px; border-radius:4px; }
.pname { font-size:14px; font-weight:bold; }
.pmeta { font-size:10px; color:#aaa; }
.statbar { display:flex; background:#f0f0f0; border-bottom:1px solid #ddd; }
.sc { text-align:center; flex:1; padding:5px 4px; border-right:1px solid #ddd; }
.sc:last-child { border-right:none; }
.sh { font-size:8px; font-weight:bold; color:#777; text-transform:uppercase; }
.sv { font-size:13px; font-weight:700; }
.sp { font-size:9px; color:#555; }
.hot  { color:#2e7d32 !important; font-weight:bold; }
.warm { color:#f57f17 !important; }
.cold { color:#b71c1c !important; font-weight:bold; }
.pbody { display:grid; grid-template-columns:1fr 1fr; }
.pleft { padding:9px 11px; border-right:1px solid #ddd; }
.pright { padding:9px 11px; }
.stitle { font-size:8.5px; font-weight:bold; color:#C8102E; text-transform:uppercase;
          letter-spacing:.5px; border-bottom:1px solid #C8102E; margin-bottom:5px; padding-bottom:2px; }
.ai-title { color:#1a1a2e; border-color:#1a1a2e; }
table.ptt { width:100%; border-collapse:collapse; font-size:10.5px; }
table.ptt th { background:#e8e8e8; padding:2px 4px; font-size:8.5px; font-weight:bold; color:#555; text-align:left; }
table.ptt td { padding:2px 4px; border-bottom:1px solid #f4f4f4; }
.warn-to { color:#b71c1c; font-weight:bold; }
.infoline { font-size:10px; margin-bottom:3px; line-height:1.5; }
.to-tag { display:inline-block; background:#fce4e4; color:#b71c1c; font-size:9px;
          border-radius:3px; padding:0 4px; margin-right:3px; font-weight:600; }
ul.notes { padding-left:13px; margin-top:0; }
ul.notes li { font-size:10.5px; margin-bottom:3px; line-height:1.5; }
.note-exploit { color:#b71c1c; font-weight:600; }
.note-caution { color:#1565C0; font-weight:600; }
.chartrow { display:grid; grid-template-columns:1fr 1fr; gap:8px; }
.footer { text-align:right; font-size:9px; color:#aaa; margin-top:10px;
          border-top:1px solid #eee; padding-top:6px; }
@page { size: A4; margin: 6mm 10mm; }
@media print {
  body { padding:0; max-width:100%; font-size:9.5px; }
  .team-section { break-after: page; page-break-after: always; }
  .page-pair { break-after: page; page-break-after: always; }
  .page-pair:last-child { break-after: auto; page-break-after: auto; }
  .pcard { break-inside: avoid; page-break-inside: avoid; margin-bottom:6px; }
  .pheader { padding:5px 10px; }
  .pnum { font-size:14px; padding:2px 7px; }
  .pname { font-size:12px; }
  .statbar .sc { padding:3px 4px; }
  .sv { font-size:11px; }
  .sh { font-size:7.5px; }
  .sp { font-size:8px; }
  .pleft, .pright { padding:5px 8px; }
  .stitle { font-size:7.5px; margin-bottom:3px; }
  .infoline { font-size:9px; margin-bottom:2px; }
  table.ptt th { font-size:7.5px; padding:1px 3px; }
  table.ptt td { font-size:9px; padding:1px 3px; }
  ul.notes li { font-size:9px; margin-bottom:2px; line-height:1.35; }
  .chartrow { gap:5px; }
  .chartrow svg { height:148px !important; width:auto !important; max-width:49%; }
  .boxbody li { font-size:9.5px; margin-bottom:2px; }
  .hdr h1 { font-size:20px; }
  .hdr { padding-bottom:6px; margin-bottom:8px; }
  .snote { padding:3px 8px; margin-bottom:8px; }
  .team-grid, .def-grid { gap:7px; margin-bottom:8px; }
}
"""

    # Embed court PNG as base64 so the HTML is fully self-contained (shareable)
    court_png = os.path.join(BASE_DIR, "shooting-map-sm.png")
    court_b64 = ""
    if os.path.exists(court_png):
        court_b64 = "data:image/png;base64," + base64.b64encode(open(court_png, "rb").read()).decode()

    court_js = f"""<script>
(function(){{
  var src = {json.dumps(court_b64)};
  if (!src) return;
  document.querySelectorAll('image[href="shooting-map-sm.png"]').forEach(function(el){{
    el.setAttribute('href', src);
  }});
}})();
</script>""" if court_b64 else ""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Canada WNT — Season Report</title><style>{css}</style></head>
<body>
<div class="hdr">
  <h1>Canada WNT (CAN)</h1>
  <div class="sub">Season Analysis — 3x3 Women's National Team &nbsp;|&nbsp; Stats: SSA DB &nbsp;·&nbsp; All analysis: Claude Opus AI &nbsp;·&nbsp; Shot charts: SSA zones</div>
</div>
<div class="snote">
  <b>3x3:</b> Inside arc = <b>1pt</b> (API: 2PT%) &nbsp;·&nbsp; Outside arc = <b>2pt</b> (API: 3PT%) &nbsp;·&nbsp; FT = <b>1pt</b>
  &nbsp;&nbsp;|&nbsp;&nbsp;
  Chart: <span style="display:inline-block;width:10px;height:10px;background:#4CAF50;border-radius:2px;vertical-align:middle"></span> ≥55% &nbsp;
  <span style="display:inline-block;width:10px;height:10px;background:#FFC107;border-radius:2px;vertical-align:middle"></span> 40–55% &nbsp;
  <span style="display:inline-block;width:10px;height:10px;background:#FF7043;border-radius:2px;vertical-align:middle"></span> 25–40% &nbsp;
  <span style="display:inline-block;width:10px;height:10px;background:#EF5350;border-radius:2px;vertical-align:middle"></span> &lt;25%
</div>
<div class="team-section">
<div class="team-grid">
  <div class="box"><div class="boxtitle">&#129302; Offensive Profile — AI</div><div class="boxbody"><ul>{off_html}</ul></div></div>
  <div class="box"><div class="boxtitle">&#129302; Transition &amp; Fouls — AI</div><div class="boxbody"><ul>{tr_html}</ul></div></div>
  <div class="box"><div class="boxtitle">Team Play Types (weighted PPP)</div><div class="boxbody">
    <table class="tpt"><thead><tr><th>Action</th><th>Poss %</th><th>PPP</th></tr></thead><tbody>{tpt_rows}</tbody></table>
  </div></div>
</div>
<div class="def-grid">
  <div class="defbox"><div class="deftitle">&#129302; Defence Overview — AI</div><div class="boxbody"><ul>{def_html}</ul></div></div>
  <div class="defbox"><div class="deftitle">&#129302; How to Attack Canada — AI</div><div class="boxbody"><ul>{opp_html}</ul></div></div>
  <div class="defbox"><div class="deftitle">&#129302; Turnover Patterns — AI</div><div class="boxbody"><ul>{to_html}</ul></div></div>
</div>
{first_card_html}
</div>
{cards_html}
<div class="footer">SSA Analytics DB &nbsp;·&nbsp; Period: SEASON &nbsp;·&nbsp; All analysis generated by Claude Opus — data only, no hallucination</div>
{court_js}
</body></html>"""

    out = os.path.join(BASE_DIR, "canada_wnt_report.html")
    with open(out, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"\nWritten → {out}")
    conn.close()

if __name__ == "__main__":
    main()
